name: mediar
channels:
  - conda-forge
dependencies:
  - _libgcc_mutex=0.1=conda_forge
  - _openmp_mutex=4.5=2_gnu
  - bzip2=1.0.8=h4bc722e_7
  - ca-certificates=2025.6.15=hbd8a1cb_0
  - ld_impl_linux-64=2.40=hf3520f5_7
  - libffi=3.4.6=h2dba641_1
  - libgcc=15.1.0=h767d61c_2
  - libgcc-ng=15.1.0=h69a702a_2
  - libgomp=15.1.0=h767d61c_2
  - liblzma=5.8.1=hb9d3cd8_2
  - liblzma-devel=5.8.1=hb9d3cd8_2
  - libnsl=2.0.1=hb9d3cd8_1
  - libsqlite=3.50.1=h6cd9bfd_6
  - libstdcxx=15.1.0=h8f9b012_2
  - libstdcxx-ng=15.1.0=h4852527_2
  - libuuid=2.38.1=h0b41bf4_0
  - libxcrypt=4.4.36=hd590300_1
  - libzlib=1.3.1=hb9d3cd8_2
  - ncurses=6.5=h2d0b736_3
  - openssl=3.5.0=h7b32b05_1
  - pip=25.0.1=pyh8b19718_0
  - python=3.9.21=h85ef794_2_cpython
  - readline=8.2=h8c095d6_2
  - setuptools=75.8.0=pyhff2d567_0
  - sqlite=3.50.1=hb7a22d2_6
  - tk=8.6.13=noxft_hd72426e_102
  - wheel=0.45.1=pyhd8ed1ab_1
  - xz=5.8.1=hbcc6ac9_2
  - xz-gpl-tools=5.8.1=hbcc6ac9_2
  - xz-tools=5.8.1=hb9d3cd8_2
  - zlib=1.3.1=hb9d3cd8_2
  - pip:
      - appdirs==1.4.4
      - certifi==2025.4.26
      - charset-normalizer==3.4.1
      - click==8.1.8
      - contourpy==1.3.0
      - cycler==0.12.1
      - docker-pycreds==0.4.0
      - efficientnet-pytorch==0.7.1
      - fastremap==1.14.1
      - filelock==3.18.0
      - fonttools==4.57.0
      - fsspec==2025.3.2
      - gitdb==4.0.12
      - gitpython==3.1.44
      - huggingface-hub==0.30.2
      - idna==3.10
      - imagecodecs==2024.12.30
      - imageio==2.37.0
      - importlib-resources==6.5.2
      - jinja2==3.1.6
      - kiwisolver==1.4.7
      - lazy-loader==0.4
      - llvmlite==0.40.1
      - markupsafe==3.0.2
      - matplotlib==3.9.4
      - monai==1.3.0
      - mpmath==1.3.0
      - munch==4.0.0
      - networkx==3.2.1
      - numba==0.57.1
      - numpy==1.24.3
      - nvidia-cublas-cu12==12.1.3.1
      - nvidia-cuda-cupti-cu12==12.1.105
      - nvidia-cuda-nvrtc-cu12==12.1.105
      - nvidia-cuda-runtime-cu12==12.1.105
      - nvidia-cudnn-cu12==8.9.2.26
      - nvidia-cufft-cu12==11.0.2.54
      - nvidia-curand-cu12==10.3.2.106
      - nvidia-cusolver-cu12==11.4.5.107
      - nvidia-cusparse-cu12==12.1.0.106
      - nvidia-nccl-cu12==2.18.1
      - nvidia-nvjitlink-cu12==12.8.93
      - nvidia-nvtx-cu12==12.1.105
      - packaging==25.0
      - pandas==2.0.3
      - pillow==11.2.1
      - pretrainedmodels==0.7.4
      - protobuf==4.25.7
      - psutil==7.0.0
      - pydicom==2.4.4
      - pynrrd==1.1.3
      - pyparsing==3.2.3
      - python-dateutil==2.9.0.post0
      - pytz==2023.3.post1
      - pyyaml==6.0.2
      - requests==2.32.3
      - safetensors==0.5.3
      - scikit-image==0.24.0
      - scipy==1.12.0
      - seaborn==0.13.2
      - segmentation-models-pytorch==0.3.3
      - sentry-sdk==2.27.0
      - setproctitle==1.3.5
      - simpleitk==2.5.2
      - six==1.17.0
      - smmap==5.0.2
      - sympy==1.14.0
      - tifffile==2023.4.12
      - timm==0.9.2
      - torch==2.1.2
      - torchvision==0.16.2
      - tqdm==4.65.0
      - triton==2.1.0
      - typing-extensions==4.13.2
      - tzdata==2025.2
      - urllib3==2.4.0
      - wandb==0.16.2
      - zipp==3.21.0